
[project]
name = "inkstitch-fonts"
version = "0.1.0"
description = "Embroidery fonts for Ink/Stitch"
readme = "README.md"
requires-python = ">=3.11"

# [build-system.targets]
# wheel = { packages = ["src/inkstitch_fonts"] }


[build-system]
requires = ["uv_build>=0.12,<0.13"]
build-backend = "uv_build"

